### ISSUE TITLE
Решить как будет выглядеть сайтег

### ISSUE THREAD

**Issue by DmitryTrish** [siberiansymfony/siberiansymfony.ru#1]
- Набросать десигн
- Запилить автоинвайтер в slack как это сделано у tomskjs
- ???
- PROFIT

**Comment by radiopapus** [comment]
Я думаю достаточно логотипа, причем мне твоя мысль насчет груди нравится.
Автоинвайтер - хорошая идея. может у tomskjs попросить?

**Comment by DmitryTrish** [comment]
Попросил автоинвайтер. Обещали подарить.
